name: Content Update

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  fetch-latest-release:
    name: Fetch Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest release tag
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const releaseTag = latestRelease.data.tag_name;
            core.setOutput('release_tag', releaseTag);

  deploy-to-static-file-host:
    name: Deploy to Static File Host
    needs: fetch-latest-release
    uses: ./.github/workflows/cd-deploy.yml
    with:
      ref: "tags/${{ needs.get_latest_release.outputs.release_tag }}"
