name: Nightly Content Update to Static File Host

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  fetch-latest-release:
    name: Fetch Latest Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "::set-output name=tag::$latest_release"

  deploy-to-static-file-host:
    name: Deploy to Static File Host
    needs: fetch-latest-release
    uses: ./.github/workflows/cd-static-file-host.yml
    with:
      ref: ${{ needs.fetch-latest-release.outputs.tag }}
